### ISSUE TITLE
[Bug]: Preverificationgas too low

### ISSUE THREAD

**Issue by sruiz-vtn** [transeptorlabs/transeptor-bundler#69]
With local node running and bundler server running, when I try to run (npm run op) to test it, it throws an error like this:
 jsonrpc: "2.0"
    id: 44
    error: {
      "code": -32602,
      "message": "preVerificationGas 46560 too low: expected at least 46836"
    }
The problem happens in the gas.utils.ts file, calcPreVerificationGas method that it is called from ValidationService.ts
![Captura de pantalla 2024-09-08 a las 23 50 07](https://github.com/user-attachments/assets/e9447829-0ac6-46e6-a279-74346a74b407)

Step to reproduce and config eth-node file:
Terminal 1 => npm run local-eth
Terminal 2 => npm run dev 
Terminal 3 => npm run op

eth-node config
![image](https://github.com/user-attachments/assets/a3e410b8-b6a5-4a42-8f17-7990ea99f4e1)

And of course I already copied to .env files the needed variables.

I have reviewed every .sol and .ts files involved in the script (npm run op) and I could solve it, is this an error from the repo or I am doing something wrong?  I use the address generated by hardhat and this accounts are already funded I do not know what is happening, could someone help me?? Thanks!!

**Comment by V00D00-child** [comment]
Hey, @sruiz-vtn there are a few errors in the script to send the `userOp`. The `send-userOp.e2e.ts` script uses`eth_estimateUserOperationGas` to calculate the `preVerificationGas` and `verificationGasLimit` gas values which returns inaccurate values causing the `userOp` to fail validation. 

I updated the script to use hard-coded values on a [separate branch](https://github.com/transeptorlabs/transeptor-bundler/blob/bugfix/gas-estimate-for-eth-estimateUserOperationGas/e2e/send-userop.e2e.ts#L220)  and updated the deposit values to pass sending `userOp` locally, but this not ideal as we would want to the values returned from [eth_estimateUserOperationGas](https://github.com/transeptorlabs/transeptor-bundler/blob/main/src/json-rpc-handler/services/Eth.ts#L91) to work properly. 

- branch with the updated script: [bugfix/gas-estimate-for-eth-estimateUserOperationGas](https://github.com/transeptorlabs/transeptor-bundler/tree/bugfix/gas-estimate-for-eth-estimateUserOperationGas)

**Comment by sruiz-vtn** [comment]
Nice!! I will test it asap.

Thanks!!!

**Comment by V00D00-child** [comment]
@sruiz-vtn pre-verification gas calc now works as expected. The fix has been merged into the [dev-0.8.0-alpha](https://github.com/transeptorlabs/transeptor-bundler/tree/dev-0.8.0-alpha) branch and will be included in the next release.
